# back_end/python_scripts/magnus_slurm.py
import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Magnus SLURM Proxy Executor")
    parser.add_argument("--working-directory", required=True, help="Job working directory")
    parser.add_argument("--slurm-script", required=True, help="Content of the shell script to run")
    parser.add_argument("--conda-environment", required=True, help="Conda environment to activate")
    parser.add_argument("--output-path", default="", help="Optional path to redirect stdout/stderr")
    
    args = parser.parse_args()

    # 1. 准备工作目录
    work_dir = Path(args.working_directory).expanduser().resolve()
    print(f"[Magnus] Setting up working directory: {work_dir}")
    os.makedirs(work_dir, exist_ok=True)

    # 2. 生成临时包装脚本
    temp_script = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.sh', prefix='magnus_runner_')
    script_path = Path(temp_script.name)
    
    try:
        wrapper_content = f"""#!/bin/bash
# --- Auto-generated by Magnus Platform ---

# A. Initialize Conda
if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
elif [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
    source "/opt/miniconda3/etc/profile.d/conda.sh"
elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/anaconda3/etc/profile.d/conda.sh"
else
    CONDA_BASE=$(conda info --base 2>/dev/null)
    if [ -n "$CONDA_BASE" ]; then
        source "$CONDA_BASE/etc/profile.d/conda.sh"
    fi
fi

# B. Activate Environment
echo "[Magnus] Activating Conda environment: {args.conda_environment}"
conda activate {args.conda_environment} || {{ echo "[Magnus] Error: Failed to activate environment '{args.conda_environment}'"; exit 1; }}

# C. Execute User Script
echo "[Magnus] Starting user script execution..."
echo "---------------------------------------------------"
set -e
{args.slurm_script}
"""
        temp_script.write(wrapper_content)
        temp_script.close()
        script_path.chmod(0o755)

        # 3. 确定本地日志路径
        if args.output_path:
            out_path = Path(args.output_path).expanduser()
            if not out_path.is_absolute():
                out_path = work_dir / out_path
        else:
            job_id = os.environ.get("SLURM_JOB_ID", "local")
            out_path = work_dir / f"slurm-{job_id}.out"

        out_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"[Magnus] Redirecting output to: {out_path} (and stdout)")

        # 4. 执行脚本 (使用 Popen 实现 Tee 效果)
        cmd = ["bash", str(script_path)]
        
        # 打开文件准备写入
        with open(out_path, "w", encoding="utf-8") as outfile:
            # 启动子进程，通过 PIPE 捕获 stdout 和 stderr
            # bufsize=1 表示行缓冲，确保实时性
            process = subprocess.Popen(
                cmd, 
                cwd=work_dir, 
                stdout=subprocess.PIPE, 
                stderr=subprocess.STDOUT, # 将 stderr 合并进 stdout
                text=True, 
                bufsize=1
            )
            
            # 实时读取输出流
            assert process.stdout is not None
            for line in process.stdout:
                # 1. 写入本地文件
                outfile.write(line)
                outfile.flush()  # 确保文件实时更新，不怕进程崩
                
                # 2. 打印到标准输出 (给 Magnus 云端看)
                sys.stdout.write(line)
                sys.stdout.flush() 

            # 等待进程结束
            return_code = process.wait()

        # 5. 检查结果
        if return_code != 0:
            print(f"[Magnus] Job failed with exit code: {return_code}")
            sys.exit(return_code)
        
        print(f"[Magnus] Job completed successfully. Log also saved to {out_path}")

    except Exception as e:
        print(f"[Magnus] Critical Error: {str(e)}")
        sys.exit(1)
        
    finally:
        # 6. 清理
        if script_path.exists():
            try:
                os.remove(script_path)
            except OSError:
                pass

if __name__ == "__main__":
    main()